language: python
addons:
  apt:
    update: true
    packages:
    - parallel
  chrome: stable
install: pip install tensorflow tensorflowjs
script:
- python export_models.py
- bash convert_models.sh
- bash serve.sh &
- google-chrome-stable --headless https://localhost:6006
