language: python
python: 3.6
addons:
  apt:
    update: true
    packages:
    - parallel
  chrome: stable
cache:
  directories:
  - ~/.keras/models/
  - ~/.cache/pip/
install: pip install tensorflow tensorflowjs
script:
- python export_models.py
- bash convert_models.sh
- bash serve.sh &
- google-chrome-stable --headless --no-sandbox https://localhost:6006
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
