language: python
python: 3.6
addons:
  chrome: stable
  firefox: stable
cache:
  directories:
  - "~/.keras/models/"
  - "~/.cache/pip/"
install:
- pip install tensorflowjs
- pip install selenium
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz -O gecko.tar.gz
- tar -xzf gecko.tar.gz
- wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -O chromedriver.zip
- unzip chromedriver.zip
- export PATH=`pwd`:$PATH
#- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"
#- sleep 3
script:
- python test_click.py
- python export_models.py
