language: python
python: 3.6
addons:
  chrome: stable
cache:
  directories:
  - "~/.keras/models/"
  - "~/.cache/pip/"
install:
- pip install tensorflowjs
- pip install selenium
- wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
#- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"
#- sleep 3
script:
- python test_click.py
- python export_models.py